packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'
overrides:
  '@strivacity/sdk-angular': workspace:*
  '@strivacity/sdk-core': workspace:*
  '@strivacity/sdk-next': workspace:*
  '@strivacity/sdk-nuxt': workspace:*
  '@strivacity/sdk-preact': workspace:*
  '@strivacity/sdk-react': workspace:*
  '@strivacity/sdk-remix': workspace:*
  '@strivacity/sdk-svelte': workspace:*
  '@strivacity/sdk-vue': workspace:*
  '@strivacity/testing': workspace:*
  '@strivacity/common': workspace:*
shellEmulator: true
autoInstallPeers: false
allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  sharp: true
  simple-git-hooks: true
