packages:
  - 'apps/*'
  - 'packages/*'
  - 'tools/*'
overrides:
  '@strivacity/sdk-angular': workspace:*
  '@strivacity/sdk-core': workspace:*
  '@strivacity/sdk-next': workspace:*
  '@strivacity/sdk-nuxt': workspace:*
  '@strivacity/sdk-svelte': workspace:*
  '@strivacity/sdk-react': workspace:*
  '@strivacity/sdk-remix': workspace:*
  '@strivacity/sdk-vue': workspace:*
  '@strivacity/testing': workspace:*
shellEmulator: true
autoInstallPeers: false
shamefullyHoist: true
allowBuilds:
  esbuild: true
  msw: true
  nx: true
  simple-git-hooks: true
  lmdb: false
  msgpackr-extract: false
  sharp: false
