name: CI

on:
  pull_request:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm run lint

  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/setup

      - name: Test
        uses: ./.github/actions/test
        with:
          target: test:ci
          test-report: reports/*.xml
          test-artifacts: |
            coverages/
            reports/
