name: "Test"

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: install deps
        run: pnpm install --frozen-lockfile

      - name: run tests
        run: pnpm run test

      - name: report coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
